stages:
    - stage: ${{ parameters.name }}
      # Will run OS stages in parallel, if there will be no dependencies
      dependsOn: []
      displayName: ${{ parameters.displayName }}
      jobs:
# TODO: Uncomment
#          - template: os-jobs.yml
#            parameters:
#                toolchain: stable
#                name: stable
#                vmImage: ${{ parameters.vmImage }}

          - template: os-jobs.yml
            parameters:
                toolchain: nightly
                name: nightly
                vmImage: ${{ parameters.vmImage }}

# TODO: Uncomment
#          - template: os-jobs.yml
#            parameters:
#                toolchain: 1.36.0
#                name: min_supported_version
#                vmImage: ${{ parameters.vmImage }}

          - template: os-coverage.yml
            parameters:
                toolchain: nightly
                name: code_coverage
                vmImage: ${{ parameters.vmImage }}
                os_flag: ${{ parameters.name }}
